name: build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'web/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'web/**'
      - '**.md'

jobs:
  build_aarch64:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install QEMU & Toolchain for `aarch64`
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Compile for aarch64
        run: |
          mkdir -p output/aarch64
          CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ python cmake_build.py
          cp build/linux/x86_64/libpocketpy.so output/aarch64
          cp main output/aarch64/main

      - uses: actions/upload-artifact@v4
        with:
          name: aarch64
          path: output

  test_aarch64:
      runs-on: ubuntu-latest
      needs: [build_aarch64]
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download aarch64 Build
        uses: actions/download-artifact@v4
        with:
          name: aarch64
          path: output/aarch64

      - name: Install QEMU for aarch64
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static

      - name: Run `libpocketpy.so` in Emulated aarch64
        run: |
          chmod +x output/aarch64/libpocketpy.so
          qemu-aarch64-static output/aarch64/libpocketpy.so

  merge:
      runs-on: ubuntu-latest
      needs: [build_aarch64]
      steps:
      - name: "Create output directory"
        run: "mkdir $GITHUB_WORKSPACE/output"
    
      - name: "Merge aarch64"
        uses: actions/download-artifact@v4
        with:
          name: aarch64
          path: $GITHUB_WORKSPACE/output/aarch64
